# Generated by Django 4.1.7 on 2023-04-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='drug_dose',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='drug_instr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
