# Generated by Django 4.1.7 on 2023-04-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_prescription_drug_dose_prescription_drug_instr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='drug_dose',
            field=models.CharField(max_length=255),
        ),
    ]
