# Generated by Django 4.1.7 on 2023-04-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=True, verbose_name='owner status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_vet',
            field=models.BooleanField(default=False, verbose_name='owner status'),
        ),
    ]
