# Generated by Django 4.1.7 on 2023-05-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(default=False, verbose_name='guest status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_vet',
            field=models.BooleanField(default=False, verbose_name='vet status'),
        ),
    ]
