# Generated by Django 4.1.7 on 2023-04-04 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_alter_prescription_drug_dose'),
        ('petprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='prescriptions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescriptions.prescription'),
        ),
    ]
