# Generated by Django 4.1.7 on 2023-04-19 20:41

from django.db import migrations, models
import petprofiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('petprofiles', '0006_remove_petprofile_image_petprofile_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=petprofiles.models.upload_to)),
            ],
        ),
        migrations.RemoveField(
            model_name='petprofile',
            name='image_url',
        ),
    ]
