# Generated by Django 4.1.7 on 2023-04-19 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petprofiles', '0007_mymodel_remove_petprofile_image_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Image',
        ),
    ]
